version: "3.7"
services:
  app:
    build:
      args:
        user: vrivasdev
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: laravel-php:8.2
    container_name: laravel-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-network
  db:
    image: mysql:8.0
    container_name: mysql-laravel
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - laravel-network
  nginx:
    image: nginx:alpine
    container_name: ninx-laravel
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge